version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-net
    volumes:
      - redis-data:/data

  redis-insights:
    image: redislabs/redisinsight:latest
    container_name: redis-insights
    ports:
      - "8001:8001"
    networks:
      - app-net
    depends_on:
      - redis

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.2
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    networks:
      - app-net
    volumes:
      - es-data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.11.2
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: '["http://es01:9200"]'
    networks:
      - app-net
    depends_on:
      - es01

  apm-server:
    image: docker.elastic.co/apm/apm-server:7.11.2
    container_name: apm-server
    environment:
      - output.elasticsearch.hosts=["http://es01:9200"]
      - apm-server.kibana.enabled=true
      - apm-server.kibana.host=http://kibana:5601
    ports:
      - "8200:8200"
    networks:
      - app-net
    depends_on:
      - es01
      - kibana

volumes:
  redis-data:
  es-data:

networks:
  app-net:
    driver: bridge
