export enum USER_STATUS {
	ACTIVE = "ACTIVE",
	DELETED = "DELETED",
}

export enum SESSION_STATUS {
	ACTIVE = "ACTIVE",
	DISABLED = "DISABLED",
	FORCE_DISABLED = "FORCE_DISABLED",
	CANCELED = "CANCELED",
}
